admin.language:
    path:     /
    defaults: { _controller: AdminBundle:Language:index }
    methods: [GET]

admin.language.create:
    path: /create
    defaults: { _controller: AdminBundle:Language:create }
    methods: [GET]

admin.language.store:
    path: /create
    defaults: { _controller: AdminBundle:Language:store }
    methods: [POST]

admin.language.edit:
    path: /{id}/edit
    defaults: { _controller: AdminBundle:Language:edit }
    methods: [GET]
    requirements: { id: "[0-9]+" }

admin.language.update:
    path: /{id}/edit
    defaults: { _controller: AdminBundle:Language:update }
    methods: [PUT]
    requirements: { id: "[0-9]+" }